### ISSUE TITLE
Accept Regex

### ISSUE THREAD

**Issue by MaikoKingma** [bart-kneepkens/miakobot#1]
Let the bot accept regex when a new spelling mistake is added

**Comment by bart-kneepkens** [comment]
@MaikoKingma Can you specify how exactly you'd see this work?
I can imagine rules that are triggered when a certain Regular Expression matches the input. However, how do you envision would the bot replace the current input with the correction?

I'm lifting this issue from 1.1.0, to be done later if there is a clear overview of the requirements.
