### ISSUE TITLE
Handle tags and URLs more carefully

### ISSUE THREAD

**Issue by MaikoKingma** [bart-kneepkens/miakobot#17]
When a tag is or contains a trigger this should be ignored.

**Comment by bart-kneepkens** [comment]
The bot should never trigger on a username tag or URL in a message.
If the a rule's correction is a username tag or URL, it should not enclose the correction in backticks, since this makes it unclickable.

**Comment by MaikoKingma** [comment]
Note that this issue was initially created because Tags got corrected. Not that corrected tags are unclickable.
Example:
When there is a person with the tag @Bob and a rule 'Bob > 🅱o🅱`. In this case the bot will correct @Bob to @🅱o🅱 which defeats the purpose of using @Bob.

**Comment by bart-kneepkens** [comment]
@MaikoKingma indeed. Hence the `The bot should never trigger on a username tag or URL in a message.` 🙂

**Comment by bart-kneepkens** [comment]
Fixed in a4ad040.
