### ISSUE TITLE
Do not ignore messages containing incorrect words that are prepended with '/'

### ISSUE THREAD

**Issue by Agadar** [bart-kneepkens/miakobot#18]
I understand the bot somehow has to be able to recognize commands, which right now is presumably done by checking for a prepended '/'. However, this results in users being able to cheat the system by typing incorrect words, prepending their message with '/', and then blasting the message into the chat without being corrected because the bot ignores such messages. This seems like a flaw.

**Comment by bart-kneepkens** [comment]
I actually already used a different solution for this problem, but I forgot to remove the previous check.

Fixed in ae27390.
