### ISSUE TITLE
Suggestion: Trigger strikedthrough, correction bold

### ISSUE THREAD

**Issue by rujacobi** [bart-kneepkens/miakobot#2]
When the trigger word is said and the replacement sentence is posted by the bot, I suggest the trigger word to be strikedthrough and the correction word added in bold after the trigger word.

**Comment by bart-kneepkens** [comment]
While this is a nice idea, it is not feasible since the Telegram API does not support strikethrough formatting at the moment. For more info: [Telegram API Formatting Options](https://core.telegram.org/bots/api#formatting-options)
