### ISSUE TITLE
Emoji are not properly persisted.  When the app restarts, this will give faulty corrections.

### ISSUE THREAD

**Issue by bart-kneepkens** [bart-kneepkens/miakobot#7]

**Comment by rujacobi** [comment]
Windows 10 here, no issues.

**Comment by bart-kneepkens** [comment]
@coooby12 turns out it's not a Windows issue, but rather an issue that occurs after loading from the persistence file.

**Comment by bart-kneepkens** [comment]
Fixed in 1be7243.
